Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -6,6 +6,9 @@ env:
   CONTINUE_ON_ERROR: false
   COVERAGE_THRESHOLD: 20
   CODE_SMELLS_THRESHOLD: 200
+  VULNERABILITIES_THRESHOLD: 6
+  
+  
 
 on:
   push:
@@ -87,19 +90,47 @@ jobs:
                     echo "Sonar code coverage Gate: Passed"
                  fi
                  
-             elif [ "$metric" == "code_smells" ] ;
-              then
-              if [ "${value%.*}" -gt ${{env.CODE_SMELLS-THRESHOLD }} ] ;
+              elif [ "$metric" == "code_smells" ] ;
+               then
+               if [ "${value%.*}" -gt ${{env.CODE_SMELLS_THRESHOLD }} ] ;
                  then
                     echo "Expected ${metric%.*} - ${{env.CODE_SMELLS_THRESHOLD}}"
                     echo "Actual ${metric%.*} - ${value%.*}"
                     echo "Sonar code coverage Gate: Failed"
                     exit 1
-                 else  
+               else  
                     echo "Expected ${metric%.*} - ${{env.CODE_SMELLS_THRESHOLD}}"
                     echo "Actual ${metric%.*} - ${value%.*}"
                     echo "Sonar code coverage Gate: Passed"
-                 fi
+               fi
+                 
+             elif [ "$metric" == "vulnerabilities" ] ;
+               then
+               if [ "${value%.*}" -gt ${{env.VULNERABILITIES_THRESHOLD }} ] ;
+                 then
+                    echo "Expected ${metric%.*} - ${{env.VULNERABILITIES_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Failed"
+                    exit 1
+               else  
+                    echo "Expected ${metric%.*} - ${{env.VULNERABILITIES_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Passed"
+               fi   
+               
+              elif [ "$metric" == "critical_violations" ] ;
+               then
+               if [ "${value%.*}" -gt ${{env.CRITICAL_VIOLATIONS_THRESHOLD }} ] ;
+                 then
+                    echo "Expected ${metric%.*} - ${{env.CRITICAL_VIOLATIONS_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Failed"
+                    exit 1
+               else  
+                    echo "Expected ${metric%.*} - ${{env.CRITICAL_VIOLATIONS_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Passed"
+               fi      
            fi      
         done <<< $(jq -c '.component.measures[]'  $PWD/Response.json) 
         cat $PWD/Response.json
